/*
 * reasons.cpp
 *
 * Part of "Dark Tower: All Hail" LARP music engine.
 *
 * Generated automatically by EmotionProcessor.py
 * from Reasons.csv
 *
 * !!! DO NOT EDIT !!!
 *
 * Generated at 2018-04-04 15:46:18
 */
#include "reasons.h"

int BEAM_ID;
int BEAM_CLOSE_ID;
int BECOME_CORRUPTED_ID;
int BECOME_CRIMSON_ID;
int BECOME_CRIMSONISH_ID;
int BECOME_CRIMSON_SERVANT_ID;
int BECOME_NEUTRAL_ID;
int BECOME_WHITE_ID;
int BECOME_WHITE_MESSENGER_ID;
int BECOME_WHITISH_ID;
int BLESSED_PLACE_ID;
int CRIMSON_BROADCAST1_ID;
int CRIMSON_BROADCAST2_ID;
int CRIMSON_BROADCAST3_ID;
int CRIMSON_FEELING_ID;
int CRIMSON_GRIEVE_ID;
int CRIMSON_KING_SONG_ID;
int CRIMSON_LAUGH_ID;
int CRIMSON_PLACE_ID;
int CRIMSON_SERVANT_ID;
int CRIMSON_SERVANT_FEELING_ID;
int DEATH_ID;
int DESTROY_KATET_ID;
int DOOR_ACTIVATED_ID;
int DOOR_FAR_ID;
int DOOR_FAR_MANNI_ID;
int DOOR_LEFT_ID;
int DOOR_NEAR_ID;
int DOOR_NEAR_MANNI_ID;
int EAGLE_ID;
int FEAR_ID;
int FEAR_PLACE_ID;
int FORM_KATET_ID;
int GERRARO_ID;
int GUNSLINGER_FEELING_ID;
int HYPNOSIS_ID;
int INFLUENCE_AT_DOGAN_ID;
int INN_ID;
int KATET_NEAR_ID;
int LION_ID;
int MANNI_ID;
int MASTERKA_ID;
int MASTER_ALIVE_ID;
int MASTER_CANCEL_CORRUPT_ID;
int MASTER_CRIMSON_ID;
int MASTER_WHITE_ID;
int MORANO_ID;
int NEUTRALIZE_ID;
int PERSON_NEAR_ID;
int REBOOT_ID;
int RESET_ID;
int ROSE_ID;
int SHOW_DOGAN_STATE_ID;
int SQUARE_ID;
int THINNY_ID;
int TIMELINE_GATHERING_ID;
int TIMELINE_TRAIN_ID;
int TIMELINE_TRAIN_ARRIVING_ID;
int TOWNHOUSE_ID;
int WHITE_FEELING_ID;
int WHITE_JOY_ID;
int WHITE_MESSENGER_ID;
int WHITE_SORROW_ID;
int PLACEHOLDER_63_ID;
int PLACEHOLDER_64_ID;
int PLACEHOLDER_65_ID;
int PLACEHOLDER_66_ID;
int PLACEHOLDER_67_ID;
int PLACEHOLDER_68_ID;
int PLACEHOLDER_69_ID;
int PLACEHOLDER_70_ID;
int PLACEHOLDER_71_ID;
int PLACEHOLDER_72_ID;
int PLACEHOLDER_73_ID;
int PLACEHOLDER_74_ID;
int PLACEHOLDER_75_ID;
int PLACEHOLDER_76_ID;
int PLACEHOLDER_77_ID;
int PLACEHOLDER_78_ID;
int PLACEHOLDER_79_ID;
int PLACEHOLDER_80_ID;
int PLACEHOLDER_81_ID;
int PLACEHOLDER_82_ID;
int PLACEHOLDER_83_ID;
int PLACEHOLDER_84_ID;
int PLACEHOLDER_85_ID;
int PLACEHOLDER_86_ID;
int PLACEHOLDER_87_ID;
int PLACEHOLDER_88_ID;
int PLACEHOLDER_89_ID;
int PLACEHOLDER_90_ID;
int PLACEHOLDER_91_ID;
int PLACEHOLDER_92_ID;
int PLACEHOLDER_93_ID;
int PLACEHOLDER_94_ID;
int PLACEHOLDER_95_ID;
int PLACEHOLDER_96_ID;
int PLACEHOLDER_97_ID;
int PLACEHOLDER_98_ID;
int PLACEHOLDER_99_ID;
int PLACEHOLDER_100_ID;
int PLACEHOLDER_101_ID;
int PLACEHOLDER_102_ID;
int PLACEHOLDER_103_ID;
int PLACEHOLDER_104_ID;
int PLACEHOLDER_105_ID;
int PLACEHOLDER_106_ID;
int PLACEHOLDER_107_ID;
int PLACEHOLDER_108_ID;
int PLACEHOLDER_109_ID;
int PLACEHOLDER_110_ID;
int PLACEHOLDER_111_ID;
int PLACEHOLDER_112_ID;
int PLACEHOLDER_113_ID;
int PLACEHOLDER_114_ID;
int PLACEHOLDER_115_ID;
int PLACEHOLDER_116_ID;
int PLACEHOLDER_117_ID;
int PLACEHOLDER_118_ID;
int PLACEHOLDER_119_ID;
int PLACEHOLDER_120_ID;
int PLACEHOLDER_121_ID;
int PLACEHOLDER_122_ID;
int PLACEHOLDER_123_ID;
int PLACEHOLDER_124_ID;
int PLACEHOLDER_125_ID;
int PLACEHOLDER_126_ID;
int PLACEHOLDER_127_ID;
int JRight_ID;
int CRandall_ID;
int RDias_ID;
int DRice_ID;
int AFlores_ID;
int Isaak_ID;
int Cordelia_ID;
int SJames_ID;
int FPibody_ID;
int RHarris_ID;
int KMurray_ID;
int PSayer_ID;
int JKuroki_ID;
int RRobin_ID;
int ALaiden_ID;
int CBendetsen_ID;
int BKuroki_ID;
int AHarmett_ID;
int ASExupery_ID;
int RParkinson1_ID;
int JMcArthur_ID;
int CTramunti_ID;
int LEsposito_ID;
int SCaracapa_ID;
int SKuroki_ID;
int SGerraro_ID;
int MGerraro_ID;
int RGerraro_ID;
int EGerraro_ID;
int GGerraro_ID;
int GMorano_ID;
int LMorano_ID;
int EMorano_ID;
int AMorano_ID;
int CMorano_ID;
int AlMorano_ID;
int Rob_ID;
int DJamison_ID;
int SJamison_ID;
int ESatton_ID;
int DSatton_ID;
int LSatton_ID;
int RParkinson_ID;
int WBray_ID;
int HBray_ID;
int BCassidy_ID;
int SWinch_ID;
int DWinch_ID;
int Ruth_ID;
int Seven_ID;
int SKing_ID;
int MParker_ID;
int Samantha_ID;
int RMcCoy_ID;

void prepare_reasons(const InfluenceTable &table)
{
    BEAM_ID = table.find("BEAM");
    BEAM_CLOSE_ID = table.find("BEAM_CLOSE");
    BECOME_CORRUPTED_ID = table.find("BECOME_CORRUPTED");
    BECOME_CRIMSON_ID = table.find("BECOME_CRIMSON");
    BECOME_CRIMSONISH_ID = table.find("BECOME_CRIMSONISH");
    BECOME_CRIMSON_SERVANT_ID = table.find("BECOME_CRIMSON_SERVANT");
    BECOME_NEUTRAL_ID = table.find("BECOME_NEUTRAL");
    BECOME_WHITE_ID = table.find("BECOME_WHITE");
    BECOME_WHITE_MESSENGER_ID = table.find("BECOME_WHITE_MESSENGER");
    BECOME_WHITISH_ID = table.find("BECOME_WHITISH");
    BLESSED_PLACE_ID = table.find("BLESSED_PLACE");
    CRIMSON_BROADCAST1_ID = table.find("CRIMSON_BROADCAST1");
    CRIMSON_BROADCAST2_ID = table.find("CRIMSON_BROADCAST2");
    CRIMSON_BROADCAST3_ID = table.find("CRIMSON_BROADCAST3");
    CRIMSON_FEELING_ID = table.find("CRIMSON_FEELING");
    CRIMSON_GRIEVE_ID = table.find("CRIMSON_GRIEVE");
    CRIMSON_KING_SONG_ID = table.find("CRIMSON_KING_SONG");
    CRIMSON_LAUGH_ID = table.find("CRIMSON_LAUGH");
    CRIMSON_PLACE_ID = table.find("CRIMSON_PLACE");
    CRIMSON_SERVANT_ID = table.find("CRIMSON_SERVANT");
    CRIMSON_SERVANT_FEELING_ID = table.find("CRIMSON_SERVANT_FEELING");
    DEATH_ID = table.find("DEATH");
    DESTROY_KATET_ID = table.find("DESTROY_KATET");
    DOOR_ACTIVATED_ID = table.find("DOOR_ACTIVATED");
    DOOR_FAR_ID = table.find("DOOR_FAR");
    DOOR_FAR_MANNI_ID = table.find("DOOR_FAR_MANNI");
    DOOR_LEFT_ID = table.find("DOOR_LEFT");
    DOOR_NEAR_ID = table.find("DOOR_NEAR");
    DOOR_NEAR_MANNI_ID = table.find("DOOR_NEAR_MANNI");
    EAGLE_ID = table.find("EAGLE");
    FEAR_ID = table.find("FEAR");
    FEAR_PLACE_ID = table.find("FEAR_PLACE");
    FORM_KATET_ID = table.find("FORM_KATET");
    GERRARO_ID = table.find("GERRARO");
    GUNSLINGER_FEELING_ID = table.find("GUNSLINGER_FEELING");
    HYPNOSIS_ID = table.find("HYPNOSIS");
    INFLUENCE_AT_DOGAN_ID = table.find("INFLUENCE_AT_DOGAN");
    INN_ID = table.find("INN");
    KATET_NEAR_ID = table.find("KATET_NEAR");
    LION_ID = table.find("LION");
    MANNI_ID = table.find("MANNI");
    MASTERKA_ID = table.find("MASTERKA");
    MASTER_ALIVE_ID = table.find("MASTER_ALIVE");
    MASTER_CANCEL_CORRUPT_ID = table.find("MASTER_CANCEL_CORRUPT");
    MASTER_CRIMSON_ID = table.find("MASTER_CRIMSON");
    MASTER_WHITE_ID = table.find("MASTER_WHITE");
    MORANO_ID = table.find("MORANO");
    NEUTRALIZE_ID = table.find("NEUTRALIZE");
    PERSON_NEAR_ID = table.find("PERSON_NEAR");
    REBOOT_ID = table.find("REBOOT");
    RESET_ID = table.find("RESET");
    ROSE_ID = table.find("ROSE");
    SHOW_DOGAN_STATE_ID = table.find("SHOW_DOGAN_STATE");
    SQUARE_ID = table.find("SQUARE");
    THINNY_ID = table.find("THINNY");
    TIMELINE_GATHERING_ID = table.find("TIMELINE_GATHERING");
    TIMELINE_TRAIN_ID = table.find("TIMELINE_TRAIN");
    TIMELINE_TRAIN_ARRIVING_ID = table.find("TIMELINE_TRAIN_ARRIVING");
    TOWNHOUSE_ID = table.find("TOWNHOUSE");
    WHITE_FEELING_ID = table.find("WHITE_FEELING");
    WHITE_JOY_ID = table.find("WHITE_JOY");
    WHITE_MESSENGER_ID = table.find("WHITE_MESSENGER");
    WHITE_SORROW_ID = table.find("WHITE_SORROW");
    PLACEHOLDER_63_ID = table.find("PLACEHOLDER_63");
    PLACEHOLDER_64_ID = table.find("PLACEHOLDER_64");
    PLACEHOLDER_65_ID = table.find("PLACEHOLDER_65");
    PLACEHOLDER_66_ID = table.find("PLACEHOLDER_66");
    PLACEHOLDER_67_ID = table.find("PLACEHOLDER_67");
    PLACEHOLDER_68_ID = table.find("PLACEHOLDER_68");
    PLACEHOLDER_69_ID = table.find("PLACEHOLDER_69");
    PLACEHOLDER_70_ID = table.find("PLACEHOLDER_70");
    PLACEHOLDER_71_ID = table.find("PLACEHOLDER_71");
    PLACEHOLDER_72_ID = table.find("PLACEHOLDER_72");
    PLACEHOLDER_73_ID = table.find("PLACEHOLDER_73");
    PLACEHOLDER_74_ID = table.find("PLACEHOLDER_74");
    PLACEHOLDER_75_ID = table.find("PLACEHOLDER_75");
    PLACEHOLDER_76_ID = table.find("PLACEHOLDER_76");
    PLACEHOLDER_77_ID = table.find("PLACEHOLDER_77");
    PLACEHOLDER_78_ID = table.find("PLACEHOLDER_78");
    PLACEHOLDER_79_ID = table.find("PLACEHOLDER_79");
    PLACEHOLDER_80_ID = table.find("PLACEHOLDER_80");
    PLACEHOLDER_81_ID = table.find("PLACEHOLDER_81");
    PLACEHOLDER_82_ID = table.find("PLACEHOLDER_82");
    PLACEHOLDER_83_ID = table.find("PLACEHOLDER_83");
    PLACEHOLDER_84_ID = table.find("PLACEHOLDER_84");
    PLACEHOLDER_85_ID = table.find("PLACEHOLDER_85");
    PLACEHOLDER_86_ID = table.find("PLACEHOLDER_86");
    PLACEHOLDER_87_ID = table.find("PLACEHOLDER_87");
    PLACEHOLDER_88_ID = table.find("PLACEHOLDER_88");
    PLACEHOLDER_89_ID = table.find("PLACEHOLDER_89");
    PLACEHOLDER_90_ID = table.find("PLACEHOLDER_90");
    PLACEHOLDER_91_ID = table.find("PLACEHOLDER_91");
    PLACEHOLDER_92_ID = table.find("PLACEHOLDER_92");
    PLACEHOLDER_93_ID = table.find("PLACEHOLDER_93");
    PLACEHOLDER_94_ID = table.find("PLACEHOLDER_94");
    PLACEHOLDER_95_ID = table.find("PLACEHOLDER_95");
    PLACEHOLDER_96_ID = table.find("PLACEHOLDER_96");
    PLACEHOLDER_97_ID = table.find("PLACEHOLDER_97");
    PLACEHOLDER_98_ID = table.find("PLACEHOLDER_98");
    PLACEHOLDER_99_ID = table.find("PLACEHOLDER_99");
    PLACEHOLDER_100_ID = table.find("PLACEHOLDER_100");
    PLACEHOLDER_101_ID = table.find("PLACEHOLDER_101");
    PLACEHOLDER_102_ID = table.find("PLACEHOLDER_102");
    PLACEHOLDER_103_ID = table.find("PLACEHOLDER_103");
    PLACEHOLDER_104_ID = table.find("PLACEHOLDER_104");
    PLACEHOLDER_105_ID = table.find("PLACEHOLDER_105");
    PLACEHOLDER_106_ID = table.find("PLACEHOLDER_106");
    PLACEHOLDER_107_ID = table.find("PLACEHOLDER_107");
    PLACEHOLDER_108_ID = table.find("PLACEHOLDER_108");
    PLACEHOLDER_109_ID = table.find("PLACEHOLDER_109");
    PLACEHOLDER_110_ID = table.find("PLACEHOLDER_110");
    PLACEHOLDER_111_ID = table.find("PLACEHOLDER_111");
    PLACEHOLDER_112_ID = table.find("PLACEHOLDER_112");
    PLACEHOLDER_113_ID = table.find("PLACEHOLDER_113");
    PLACEHOLDER_114_ID = table.find("PLACEHOLDER_114");
    PLACEHOLDER_115_ID = table.find("PLACEHOLDER_115");
    PLACEHOLDER_116_ID = table.find("PLACEHOLDER_116");
    PLACEHOLDER_117_ID = table.find("PLACEHOLDER_117");
    PLACEHOLDER_118_ID = table.find("PLACEHOLDER_118");
    PLACEHOLDER_119_ID = table.find("PLACEHOLDER_119");
    PLACEHOLDER_120_ID = table.find("PLACEHOLDER_120");
    PLACEHOLDER_121_ID = table.find("PLACEHOLDER_121");
    PLACEHOLDER_122_ID = table.find("PLACEHOLDER_122");
    PLACEHOLDER_123_ID = table.find("PLACEHOLDER_123");
    PLACEHOLDER_124_ID = table.find("PLACEHOLDER_124");
    PLACEHOLDER_125_ID = table.find("PLACEHOLDER_125");
    PLACEHOLDER_126_ID = table.find("PLACEHOLDER_126");
    PLACEHOLDER_127_ID = table.find("PLACEHOLDER_127");
    JRight_ID = table.find("JRight");
    CRandall_ID = table.find("CRandall");
    RDias_ID = table.find("RDias");
    DRice_ID = table.find("DRice");
    AFlores_ID = table.find("AFlores");
    Isaak_ID = table.find("Isaak");
    Cordelia_ID = table.find("Cordelia");
    SJames_ID = table.find("SJames");
    FPibody_ID = table.find("FPibody");
    RHarris_ID = table.find("RHarris");
    KMurray_ID = table.find("KMurray");
    PSayer_ID = table.find("PSayer");
    JKuroki_ID = table.find("JKuroki");
    RRobin_ID = table.find("RRobin");
    ALaiden_ID = table.find("ALaiden");
    CBendetsen_ID = table.find("CBendetsen");
    BKuroki_ID = table.find("BKuroki");
    AHarmett_ID = table.find("AHarmett");
    ASExupery_ID = table.find("ASExupery");
    RParkinson1_ID = table.find("RParkinson1");
    JMcArthur_ID = table.find("JMcArthur");
    CTramunti_ID = table.find("CTramunti");
    LEsposito_ID = table.find("LEsposito");
    SCaracapa_ID = table.find("SCaracapa");
    SKuroki_ID = table.find("SKuroki");
    SGerraro_ID = table.find("SGerraro");
    MGerraro_ID = table.find("MGerraro");
    RGerraro_ID = table.find("RGerraro");
    EGerraro_ID = table.find("EGerraro");
    GGerraro_ID = table.find("GGerraro");
    GMorano_ID = table.find("GMorano");
    LMorano_ID = table.find("LMorano");
    EMorano_ID = table.find("EMorano");
    AMorano_ID = table.find("AMorano");
    CMorano_ID = table.find("CMorano");
    AlMorano_ID = table.find("AlMorano");
    Rob_ID = table.find("Rob");
    DJamison_ID = table.find("DJamison");
    SJamison_ID = table.find("SJamison");
    ESatton_ID = table.find("ESatton");
    DSatton_ID = table.find("DSatton");
    LSatton_ID = table.find("LSatton");
    RParkinson_ID = table.find("RParkinson");
    WBray_ID = table.find("WBray");
    HBray_ID = table.find("HBray");
    BCassidy_ID = table.find("BCassidy");
    SWinch_ID = table.find("SWinch");
    DWinch_ID = table.find("DWinch");
    Ruth_ID = table.find("Ruth");
    Seven_ID = table.find("Seven");
    SKing_ID = table.find("SKing");
    MParker_ID = table.find("MParker");
    Samantha_ID = table.find("Samantha");
    RMcCoy_ID = table.find("RMcCoy");
}

// End of reasons.cpp
