/*
 * reasons.h
 *
 * Part of "Dark Tower: All Hail" LARP music engine.
 *
 * Generated automatically by EmotionProcessor.py
 * from Reasons.csv
 *
 * !!! DO NOT EDIT !!!
 *
 * Generated at 2018-04-04 15:46:18
 */
#ifndef REASONS_H
#define REASONS_H

enum
{
    BEAM_ID = 0,
    BEAM_CLOSE_ID = 1,
    BECOME_CORRUPTED_ID = 2,
    BECOME_CRIMSON_ID = 3,
    BECOME_CRIMSONISH_ID = 4,
    BECOME_CRIMSON_SERVANT_ID = 5,
    BECOME_NEUTRAL_ID = 6,
    BECOME_WHITE_ID = 7,
    BECOME_WHITE_MESSENGER_ID = 8,
    BECOME_WHITISH_ID = 9,
    BLESSED_PLACE_ID = 10,
    CRIMSON_BROADCAST1_ID = 11,
    CRIMSON_BROADCAST2_ID = 12,
    CRIMSON_BROADCAST3_ID = 13,
    CRIMSON_FEELING_ID = 14,
    CRIMSON_GRIEVE_ID = 15,
    CRIMSON_KING_SONG_ID = 16,
    CRIMSON_LAUGH_ID = 17,
    CRIMSON_PLACE_ID = 18,
    CRIMSON_SERVANT_ID = 19,
    CRIMSON_SERVANT_FEELING_ID = 20,
    DEATH_ID = 21,
    DESTROY_KATET_ID = 22,
    DOOR_ACTIVATED_ID = 23,
    DOOR_FAR_ID = 24,
    DOOR_FAR_MANNI_ID = 25,
    DOOR_LEFT_ID = 26,
    DOOR_NEAR_ID = 27,
    DOOR_NEAR_MANNI_ID = 28,
    EAGLE_ID = 29,
    FEAR_ID = 30,
    FEAR_PLACE_ID = 31,
    FORM_KATET_ID = 32,
    GERRARO_ID = 33,
    GUNSLINGER_FEELING_ID = 34,
    HYPNOSIS_ID = 35,
    INFLUENCE_AT_DOGAN_ID = 36,
    INN_ID = 37,
    KATET_NEAR_ID = 38,
    LION_ID = 39,
    MANNI_ID = 40,
    MASTERKA_ID = 41,
    MASTER_ALIVE_ID = 42,
    MASTER_CANCEL_CORRUPT_ID = 43,
    MASTER_CRIMSON_ID = 44,
    MASTER_WHITE_ID = 45,
    MORANO_ID = 46,
    NEUTRALIZE_ID = 47,
    PERSON_NEAR_ID = 48,
    REBOOT_ID = 49,
    RESET_ID = 50,
    ROSE_ID = 51,
    SHOW_DOGAN_STATE_ID = 52,
    SQUARE_ID = 53,
    THINNY_ID = 54,
    TIMELINE_GATHERING_ID = 55,
    TIMELINE_TRAIN_ID = 56,
    TIMELINE_TRAIN_ARRIVING_ID = 57,
    TOWNHOUSE_ID = 58,
    WHITE_FEELING_ID = 59,
    WHITE_JOY_ID = 60,
    WHITE_MESSENGER_ID = 61,
    WHITE_SORROW_ID = 62,
    DEAD_ID = 63,
    DOOR_VOICE_ID = 64,
    DOOR_ID = 65,
    JRight_ID = 128,
    CRandall_ID = 129,
    RDias_ID = 130,
    DRice_ID = 131,
    AFlores_ID = 132,
    Isaak_ID = 133,
    Cordelia_ID = 134,
    SJames_ID = 135,
    FPibody_ID = 136,
    RHarris_ID = 137,
    KMurray_ID = 138,
    PSayer_ID = 139,
    JKuroki_ID = 140,
    RRobin_ID = 141,
    ALaiden_ID = 142,
    CBendetsen_ID = 143,
    BKuroki_ID = 144,
    AHarmett_ID = 145,
    ASExupery_ID = 146,
    RParkinson1_ID = 147,
    JMcArthur_ID = 148,
    CTramunti_ID = 149,
    LEsposito_ID = 150,
    SCaracapa_ID = 151,
    SKuroki_ID = 152,
    SGerraro_ID = 153,
    MGerraro_ID = 154,
    RGerraro_ID = 155,
    EGerraro_ID = 156,
    GGerraro_ID = 157,
    GMorano_ID = 158,
    LMorano_ID = 159,
    EMorano_ID = 160,
    AMorano_ID = 161,
    CMorano_ID = 162,
    AlMorano_ID = 163,
    Rob_ID = 164,
    DJamison_ID = 165,
    SJamison_ID = 166,
    ESatton_ID = 167,
    DSatton_ID = 168,
    LSatton_ID = 169,
    RParkinson_ID = 170,
    WBray_ID = 171,
    HBray_ID = 172,
    BCassidy_ID = 173,
    SWinch_ID = 174,
    DWinch_ID = 175,
    Ruth_ID = 176,
    Seven_ID = 177,
    SKing_ID = 178,
    MParker_ID = 179,
    Samantha_ID = 180,
    RMcCoy_ID = 181,
};

#endif // ifdef REASONS_H

// End of reasons.h
